const labels=['周一','周二','周三','周四','周五','周六','周日'];
const numbers=[13,14,15,16,17,18,19];
const goals=[
  {id:1,title:'英语日常交流 / 阅读没问题',priority:'P0',rank:1,actions:[{name:'背墨墨单词',dimension:'单词',duration:'30 分钟'},{name:'跟读语境视频',dimension:'发音',duration:'30 分钟'},{name:'英语语法练习',dimension:'语法',duration:'1 小时'}]},
  {id:2,title:'养成看知识内容的习惯',priority:'P0',rank:2,actions:[{name:'观看一个深度视频',dimension:'输入',duration:'30 分钟'},{name:'记录一个新观点',dimension:'输出',duration:'10 分钟'}]},
  {id:3,title:'运动，让身体更有活力',priority:'P0',rank:3,actions:[{name:'慢跑或力量训练',dimension:'体能',duration:'45 分钟'}]}
];
const tasks=[
  [{time:'09:30',text:'本周项目复盘',type:'work',done:true},{time:'20:00',text:'背墨墨单词',type:'focus',goal:1}],
  [{time:'10:00',text:'设计评审会',type:'work',done:true},{time:'19:30',text:'慢跑 5 公里',type:'life',goal:3}],
  [{time:'09:00',text:'撰写周报',type:'work'},{time:'20:00',text:'背墨墨单词',type:'focus',goal:1,done:true}],
  [{time:'11:00',text:'和小林同步方案',type:'work',done:true}],
  [{time:'09:30',text:'深度工作：产品稿',type:'focus'},{time:'20:00',text:'英语语法练习',type:'focus',goal:1}],
  [{time:'10:00',text:'逛花市',type:'life',done:true},{time:'16:00',text:'整理房间',type:'life'}],
  [{time:'',text:'什么都不安排',type:'focus',done:true}]
];
const categories=['work','life','focus'];const goalColors=['#ed7042','#6e99a6','#7eaa70','#b887d7','#d4a654','#ca7b90'];
function restoreState(){try{const saved=JSON.parse(localStorage.getItem('weekful-planner-data'));if(!saved)return;if(Array.isArray(saved.goals))goals.splice(0,goals.length,...saved.goals);if(Array.isArray(saved.tasks))tasks.splice(0,tasks.length,...saved.tasks);if(Array.isArray(saved.categories))saved.categories.forEach(category=>{if(!categories.includes(category))categories.push(category)})}catch(error){console.warn('无法读取已保存的计划',error)}}
function saveState(){try{localStorage.setItem('weekful-planner-data',JSON.stringify({goals,tasks,categories}));scheduleCloudSync()}catch(error){console.warn('无法保存计划',error)}}
restoreState();goals.forEach((goal,index)=>{if(!goal.color)goal.color=goalColors[index%goalColors.length]});let nextTaskId=1;tasks.flat().forEach(task=>{if(!task.id)task.id=nextTaskId++;else nextTaskId=Math.max(nextTaskId,task.id+1)});
const $=s=>document.querySelector(s); const grid=$('#weekGrid'); const taskDialog=$('#taskDialog'); const goalDialog=$('#goalDialog'); const actionDialog=$('#actionDialog'); const cloudDialog=$('#cloudDialog'); let chosenDay=0; let editingAction=null; let editingGoal=null; let batchMode=false; const selectedTaskIds=new Set();
function clearGoalDropHints(){document.querySelectorAll('.goal-card.drop-before,.goal-card.drop-after,.goal-table tr.drop-before,.goal-table tr.drop-after').forEach(item=>item.classList.remove('drop-before','drop-after'))}
function showGoalDropHint(element,event){event.preventDefault();clearGoalDropHints();const rect=element.getBoundingClientRect();element.classList.add(event.clientY<rect.top+rect.height/2?'drop-before':'drop-after')}
function moveGoal(fromId,targetId,position){if(fromId===targetId)return;const fromIndex=goals.findIndex(goal=>goal.id===fromId);const targetIndex=goals.findIndex(goal=>goal.id===targetId);let insertIndex=targetIndex+(position==='after'?1:0);const [moved]=goals.splice(fromIndex,1);if(fromIndex<insertIndex)insertIndex--;goals.splice(insertIndex,0,moved);goals.forEach((goal,index)=>goal.rank=index+1);renderGoals()}

function renderGoals(){
  saveState();
  const root=$('#goalsGrid'); root.innerHTML='';
  renderGoalTable();
  [...goals].sort((a,b)=>a.rank-b.rank).forEach(goal=>{const card=document.createElement('article');card.id=`goal-card-${goal.id}`;card.className=`goal-card priority-${goal.priority.toLowerCase()}`;card.style.setProperty('--goal-color',goal.color);card.draggable=true;card.dataset.goal=goal.id;card.innerHTML=`<div class="goal-meta"><span class="priority-pill ${goal.priority.toLowerCase()}">${goal.priority} · 优先</span><span class="rank"># ${goal.rank}</span><span class="goal-controls"><button class="goal-control goal-edit" title="编辑目标">✎</button><button class="goal-control goal-delete" title="删除目标">×</button></span></div><h3>${goal.title}</h3><div class="action-list">${goal.actions.map((a,i)=>`<div class="action-row" draggable="true" data-goal="${goal.id}" data-action="${i}"><span class="drag-handle" title="拖动排序">⠿</span><button class="action-edit" title="编辑行动项"><span class="action-dimension">${a.dimension||'行动'}</span><span>${a.name}</span><span class="action-duration">${a.duration||'待估时'}</span></button><button class="action-delete" title="删除行动项" aria-label="删除 ${a.name}">×</button></div>`).join('')}</div><button class="add-action" data-goal="${goal.id}">+ 拆解行动项</button>`;root.append(card)});
  const empty=document.createElement('button');empty.className='goal-empty';empty.textContent='+ 添加整体目标';empty.onclick=()=>goalDialog.showModal();root.append(empty);
  root.querySelectorAll('.add-action').forEach(btn=>btn.onclick=()=>openAction(+btn.dataset.goal));
  root.querySelectorAll('.action-edit').forEach(btn=>btn.onclick=()=>{const row=btn.closest('.action-row');openAction(+row.dataset.goal,+row.dataset.action)});
  root.querySelectorAll('.action-delete').forEach(btn=>btn.onclick=()=>{const row=btn.closest('.action-row');const goal=goals.find(g=>g.id===+row.dataset.goal);goal.actions.splice(+row.dataset.action,1);renderGoals();fillGoalOptions(goal.id)});
  root.querySelectorAll('.action-row').forEach(row=>{row.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',JSON.stringify({goal:+row.dataset.goal,index:+row.dataset.action}));row.classList.add('dragging')});row.addEventListener('dragend',()=>row.classList.remove('dragging'));row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();const from=JSON.parse(e.dataTransfer.getData('text/plain'));const targetGoal=+row.dataset.goal;const targetIndex=+row.dataset.action;if(from.goal!==targetGoal||from.index===targetIndex)return;const goal=goals.find(g=>g.id===targetGoal);const [moved]=goal.actions.splice(from.index,1);goal.actions.splice(targetIndex,0,moved);renderGoals();fillGoalOptions(goal.id)})});
  root.querySelectorAll('.goal-edit').forEach(btn=>btn.onclick=()=>openGoal(+btn.closest('.goal-card').dataset.goal));
  root.querySelectorAll('.goal-delete').forEach(btn=>btn.onclick=()=>{const id=+btn.closest('.goal-card').dataset.goal;if(window.confirm('删除这个目标及其行动项吗？')){goals.splice(goals.findIndex(g=>g.id===id),1);renderGoals();fillGoalOptions()}});
  root.querySelectorAll('.goal-card').forEach(card=>{card.addEventListener('dragstart',e=>{if(e.target.closest('.action-row'))return;e.dataTransfer.setData('goal-id',card.dataset.goal);card.classList.add('dragging')});card.addEventListener('dragend',()=>{card.classList.remove('dragging');clearGoalDropHints()});card.addEventListener('dragover',e=>showGoalDropHint(card,e));card.addEventListener('dragleave',()=>card.classList.remove('drop-before','drop-after'));card.addEventListener('drop',e=>{e.preventDefault();const from=+e.dataTransfer.getData('goal-id');const position=card.classList.contains('drop-after')?'after':'before';clearGoalDropHints();if(from)moveGoal(from,+card.dataset.goal,position)})});
}
function renderGoalTable(){const body=$('#goalTableBody');body.innerHTML=[...goals].sort((a,b)=>a.rank-b.rank).map(goal=>`<tr draggable="true" data-goal="${goal.id}" style="--goal-color:${goal.color}"><td><span class="table-drag" title="拖动排序">⠿</span>${goal.title}</td><td><span class="table-priority">${goal.priority}</span></td><td><span class="table-rank">${goal.rank}</span></td><td><span class="table-actions">${goal.actions.length} 项行动</span></td><td><button class="table-edit" title="编辑目标">编辑</button></td></tr>`).join('');body.querySelectorAll('tr').forEach(row=>{row.onclick=()=>{const card=$(`#goal-card-${row.dataset.goal}`);if(!card)return;document.querySelectorAll('.goal-card.goal-focus').forEach(item=>item.classList.remove('goal-focus'));document.querySelectorAll('.goal-table tr.focused').forEach(item=>item.classList.remove('focused'));row.classList.add('focused');card.classList.add('goal-focus');card.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>card.classList.remove('goal-focus'),1400)};row.addEventListener('dragstart',e=>{e.dataTransfer.setData('goal-id',row.dataset.goal);row.classList.add('dragging')});row.addEventListener('dragend',()=>{row.classList.remove('dragging');clearGoalDropHints()});row.addEventListener('dragover',e=>showGoalDropHint(row,e));row.addEventListener('dragleave',()=>row.classList.remove('drop-before','drop-after'));row.addEventListener('drop',e=>{e.preventDefault();const from=+e.dataTransfer.getData('goal-id');const position=row.classList.contains('drop-after')?'after':'before';clearGoalDropHints();if(from)moveGoal(from,+row.dataset.goal,position)})});body.querySelectorAll('.table-edit').forEach(button=>button.onclick=e=>{e.stopPropagation();openGoal(+button.closest('tr').dataset.goal)})}
function renderWeek(){
  saveState();
  grid.innerHTML='';grid.classList.toggle('batch-mode',batchMode);tasks.forEach((items,i)=>{const col=document.createElement('article');col.className='day-column '+(i===6?'today-col':'');col.innerHTML=`<div class="day-head"><span class="dow">${labels[i]}</span><strong>${numbers[i]}</strong></div>`;items.forEach(task=>{const el=document.createElement('div');const linkedGoal=goals.find(goal=>goal.id===task.goal);el.className=`task ${linkedGoal?'goal-linked':'focus'}${task.done?' done':''}`;if(linkedGoal)el.style.setProperty('--task-color',linkedGoal.color);el.innerHTML=`<input class="task-select" type="checkbox" ${selectedTaskIds.has(task.id)?'checked':''} aria-label="选择 ${task.text}"><span>${task.text}</span>`;el.onclick=()=>{if(!batchMode){task.done=!task.done;renderWeek();updateProgress()}};el.querySelector('.task-select').onclick=e=>e.stopPropagation();el.querySelector('.task-select').onchange=e=>{e.target.checked?selectedTaskIds.add(task.id):selectedTaskIds.delete(task.id);updateBatchControls()};col.append(el)});const add=document.createElement('button');add.className='add-inline';add.textContent='+ 添加';add.onclick=()=>openTask(i);col.append(add);grid.append(col)});updateProgress();updateBatchControls()
}
function updateProgress(){const text=$('#progressText');if(!text)return;const all=tasks.flat();const done=all.filter(x=>x.done).length;text.textContent=`${done} / ${all.length}`;$('#progressBar').style.width=`${all.length?done/all.length*100:0}%`;$('.progress-card p').textContent=done===all.length?'这一周的计划都完成了，真棒。':done>=all.length/2?'已经完成一半，保持这个节奏。':'从最小的一件开始，也很好。'}
function fillGoalOptions(selected){const select=$('#taskGoal');select.innerHTML='<option value="">不关联目标</option>'+goals.map(g=>`<option value="${g.id}">${g.priority} · ${g.title}</option>`).join('');if(selected)select.value=selected; fillActionOptions()}
function fillActionOptions(){const goal=goals.find(g=>g.id===+$('#taskGoal').value);$('#taskAction').innerHTML='<option value="">自由安排</option>'+(goal?goal.actions.map(a=>`<option>${a.name}</option>`).join(''):'')}
function openTask(day=0,goal){chosenDay=day;$('#taskDay').value=day;fillGoalOptions(goal);taskDialog.showModal();setTimeout(()=>$('#taskName').focus(),50)}

$('#openModal').onclick=()=>openTask();$('#openModalBottom').onclick=()=>openTask();$('#openGoalModal').onclick=()=>openGoal();
document.querySelectorAll('[data-close]').forEach(btn=>btn.onclick=()=>document.getElementById(btn.dataset.close).close());
$('#taskDay').innerHTML=labels.map((l,i)=>`<option value="${i}">${l} · ${numbers[i]}日</option>`).join('');
$('#weekdayChoices').innerHTML=labels.map((l,i)=>`<label><input type="checkbox" value="${i}"><span>${l.slice(1)}</span></label>`).join('');
$('#taskGoal').onchange=fillActionOptions;
$('#repeatType').onchange=e=>$('.weekday-picker').classList.toggle('show',e.target.value==='custom');
$('#taskAction').onchange=e=>{if(e.target.value)$('#taskName').value=e.target.value};
$('#taskForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const text=$('#taskName').value.trim();if(!text)return;const start=+$('#taskDay').value;const repeat=$('#repeatType').value;let days=repeat==='daily'?[0,1,2,3,4,5,6]:repeat==='alternate'?[start,...[1,2,3].map(n=>start+n*2).filter(n=>n<7)]:repeat==='custom'?[...document.querySelectorAll('#weekdayChoices input:checked')].map(x=>+x.value):[start];if(!days.length)days=[start];days.forEach(day=>tasks[day].push({id:nextTaskId++,text,goal:+$('#taskGoal').value||undefined}));$('#taskName').value='';taskDialog.close();renderWeek()});
function openGoal(id){editingGoal=id?goals.find(g=>g.id===id):null;$('#goalName').value=editingGoal?.title||'';$('#goalPriority').value=editingGoal?.priority||'P0';$('#goalRank').value=editingGoal?.rank||goals.length+1;$('#goalColor').value=editingGoal?.color||goalColors[goals.length%goalColors.length];goalDialog.showModal();setTimeout(()=>$('#goalName').focus(),50)}
$('#goalForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const title=$('#goalName').value.trim();if(!title)return;const data={title,priority:$('#goalPriority').value,rank:+$('#goalRank').value,color:$('#goalColor').value};if(editingGoal)Object.assign(editingGoal,data);else goals.push({id:Date.now(),...data,actions:[]});goals.sort((a,b)=>a.rank-b.rank);goalDialog.close();renderGoals();fillGoalOptions()});
function updateBatchControls(){$('#toggleBatch').classList.toggle('active',batchMode);$('#toggleBatch').textContent=batchMode?'完成管理':'批量管理';$('#batchDelete').disabled=selectedTaskIds.size===0}
$('#toggleBatch').onclick=()=>{batchMode=!batchMode;if(!batchMode)selectedTaskIds.clear();renderWeek()};
$('#batchDelete').onclick=()=>{if(!selectedTaskIds.size)return;tasks.forEach((items,i)=>tasks[i]=items.filter(task=>!selectedTaskIds.has(task.id)));selectedTaskIds.clear();renderWeek()};
function openAction(goalId,actionIndex){const goal=goals.find(g=>g.id===goalId);editingAction={goalId,actionIndex};const action=Number.isInteger(actionIndex)?goal.actions[actionIndex]:null;$('#actionDialogTitle').textContent=action?'编辑行动项':`拆解「${goal.title}」`;$('#actionName').value=action?.name||'';$('#actionDimension').value=action?.dimension||'';$('#actionDuration').value=action?.duration||'';actionDialog.showModal();setTimeout(()=>$('#actionName').focus(),50)}
$('#actionForm').addEventListener('submit',e=>{e.preventDefault();const action={name:$('#actionName').value.trim(),dimension:$('#actionDimension').value.trim(),duration:$('#actionDuration').value.trim()||'待估时'};if(!action.name)return;const goal=goals.find(g=>g.id===editingAction.goalId);if(Number.isInteger(editingAction.actionIndex))goal.actions[editingAction.actionIndex]=action;else goal.actions.push(action);actionDialog.close();renderGoals();fillGoalOptions(goal.id)});
let cloudUser=localStorage.getItem('weekful-cloud-user')||'';let cloudToken=localStorage.getItem('weekful-cloud-token')||'';let cloudGist=localStorage.getItem('weekful-cloud-gist')||'';let cloudTimer=null;const GIST_FILE='weekful-planner-data.json';
function cloudHeaders(){return {'Authorization':`Bearer ${cloudToken}`,'Accept':'application/vnd.github+json','Content-Type':'application/json'}}
function cloudPayload(){return {goals,tasks,categories,updatedAt:new Date().toISOString()}}
function setCloudStatus(message,type=''){const status=$('#cloudStatus');status.textContent=message;status.className=`cloud-status ${type}`}
function updateCloudUI(){const connected=!!(cloudToken&&cloudGist);$('#cloudSetup').hidden=connected;$('#cloudConnected').hidden=!connected;$('#openCloudDialog').classList.toggle('connected',connected);if(connected){$('#cloudAccount').textContent=`${cloudUser} · 已连接 GitHub Gist`;$('#cloudLastSync').textContent=localStorage.getItem('weekful-last-sync')||'准备同步'}}
async function findOrCreateCloudGist(){const response=await fetch('https://api.github.com/gists?per_page=100',{headers:cloudHeaders()});if(!response.ok)throw new Error(`无法读取 Gist（${response.status}）`);const list=await response.json();const existing=list.find(gist=>gist.files&&gist.files[GIST_FILE]);if(existing)return existing.id;const created=await fetch('https://api.github.com/gists',{method:'POST',headers:cloudHeaders(),body:JSON.stringify({description:'Weekful 周计划表数据',public:false,files:{[GIST_FILE]:{content:JSON.stringify(cloudPayload())}}})});if(!created.ok)throw new Error(`无法创建 Gist（${created.status}）`);return (await created.json()).id}
function applyCloudPayload(data){if(!data)return;if(Array.isArray(data.goals))goals.splice(0,goals.length,...data.goals);if(Array.isArray(data.tasks))tasks.splice(0,tasks.length,...data.tasks);if(Array.isArray(data.categories)){categories.splice(0,categories.length,...data.categories)}goals.forEach((goal,index)=>{if(!goal.color)goal.color=goalColors[index%goalColors.length]});nextTaskId=1;tasks.flat().forEach(task=>{if(!task.id)task.id=nextTaskId++;else nextTaskId=Math.max(nextTaskId,task.id+1)});localStorage.setItem('weekful-planner-data',JSON.stringify({goals,tasks,categories}))}
async function pullCloud(manual=false){if(!cloudToken||!cloudGist)return;setCloudStatus('正在下载云端数据…');try{const response=await fetch(`https://api.github.com/gists/${cloudGist}`,{headers:cloudHeaders()});if(!response.ok)throw new Error(`下载失败（${response.status}）`);const gist=await response.json();const content=gist.files?.[GIST_FILE]?.content;if(content){applyCloudPayload(JSON.parse(content));renderGoals();renderWeek();fillGoalOptions()}const stamp=`已同步 · ${new Date().toLocaleString('zh-CN')}`;localStorage.setItem('weekful-last-sync',stamp);updateCloudUI();setCloudStatus(stamp,'success')}catch(error){setCloudStatus(error.message,'error')}}
async function pushCloud(manual=false){if(!cloudToken||!cloudGist)return;try{if(manual)setCloudStatus('正在同步…');const response=await fetch(`https://api.github.com/gists/${cloudGist}`,{method:'PATCH',headers:cloudHeaders(),body:JSON.stringify({files:{[GIST_FILE]:{content:JSON.stringify(cloudPayload())}}})});if(!response.ok)throw new Error(`同步失败（${response.status}）`);const stamp=`已同步 · ${new Date().toLocaleString('zh-CN')}`;localStorage.setItem('weekful-last-sync',stamp);updateCloudUI();if(manual)setCloudStatus(stamp,'success')}catch(error){if(manual)setCloudStatus(error.message,'error')}}
function scheduleCloudSync(){if(!cloudToken||!cloudGist)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>pushCloud(),1200)}
$('#openCloudDialog').onclick=()=>{updateCloudUI();setCloudStatus('');cloudDialog.showModal()};
$('#connectCloud').onclick=async()=>{const user=$('#cloudUser').value.trim();const token=$('#cloudToken').value.trim();if(!user||!token){setCloudStatus('请填写 GitHub 用户名和 Token。','error');return}setCloudStatus('正在验证 GitHub 连接…');try{const verify=await fetch('https://api.github.com/user',{headers:{'Authorization':`Bearer ${token}`,'Accept':'application/vnd.github+json'}});if(!verify.ok)throw new Error('Token 无效，或尚未勾选 gist 权限。');cloudUser=user;cloudToken=token;cloudGist=await findOrCreateCloudGist();localStorage.setItem('weekful-cloud-user',cloudUser);localStorage.setItem('weekful-cloud-token',cloudToken);localStorage.setItem('weekful-cloud-gist',cloudGist);updateCloudUI();await pullCloud()}catch(error){setCloudStatus(error.message,'error')}};
$('#pullCloud').onclick=()=>pullCloud(true);$('#pushCloud').onclick=()=>pushCloud(true);$('#disconnectCloud').onclick=()=>{cloudUser='';cloudToken='';cloudGist='';localStorage.removeItem('weekful-cloud-user');localStorage.removeItem('weekful-cloud-token');localStorage.removeItem('weekful-cloud-gist');updateCloudUI();setCloudStatus('已断开，当前本地数据不会被删除。')};
const dates=$('#dates');for(let i=1;i<=31;i++){const d=document.createElement('span');d.textContent=i;if(i>=13&&i<=19)d.className='week';if(i===19)d.className='today';dates.append(d)}
updateCloudUI();renderGoals();renderWeek();fillGoalOptions();if(cloudToken&&cloudGist)pullCloud();
